### ISSUE TITLE
汉化不完全，sidebar和tab的汉字显示异常

### ISSUE THREAD

**Issue by shikelong** [rexdf/Chinese-Localization#5]
![qq 20150802001956](https://cloud.githubusercontent.com/assets/4499997/9022555/68f10c32-38ac-11e5-8e18-ca3f7f39ebfb.png)

![qq 20150802001947](https://cloud.githubusercontent.com/assets/4499997/9022556/7fe1d37c-38ac-11e5-9d21-cd170ac4a0b3.png)

如图。谢谢
@rexdf

**Comment by shikelong** [comment]
怎么取消本地化？ 禁用和卸载好像都不行。。。虽然文件名是中文的情况比较少。 但是还是希望找到一个可逆的解决方法

**Comment by rexdf** [comment]
什么系统？Linux吗？这个和汉化(本插件)无关，sublime自己现实的菜单我没办法的。
首先确认下这是否是属于编码问题(locale)，然后确认下你系统的字库装的是否完全。

**Comment by rexdf** [comment]
你要取消本地化，改成英语。然后卸载即可。这就是我为何带英语支持的原因。

**Comment by shikelong** [comment]
window系统。相同的文件用未汉化的tx2打开是正常的。我按照你说的试一试。谢谢

**Comment by rexdf** [comment]
这个问题比较奇怪了。难道你用的sublime2？sublime2的支持，我只是放上去凑数的，基本上没有优化过。关键的技术优化是在sublime3上做。估计是gbk编码的问题了，嗯，明天我找个sublime2试试。

另外推荐个网址 https://gist.github.com/sublime-crack4/c11dd67cff63fcbf050e  (我几分钟后删除这句话)。

**Comment by shikelong** [comment]
我用的3.。另外我把语言切换到中文。 然后删除了插件 还是那样

**Comment by rexdf** [comment]
确认一点即可。没有装任何插件的sublime text3，有没有问题。要是有问题我就关注下。

**Comment by shikelong** [comment]
我想问一下你的汉化怎么解除 。切回英文然后禁用，卸载都没用。  我卸载了我的st3重新装了也没用。

**Comment by rexdf** [comment]
你看过项目主页上面的动图了吗？可以切换日语，繁体，简体，英语。

切换英语了吗？

> 切回英文然后禁用，卸载都没用。 

什么叫做卸载了都没用？

聊了这么多本来可以在第一个对话里面就描述清楚的，首先什么平台(win/linux/osx)，什么版本(sublime  text 2/3 x86 x64)，如何重现。 这是包bug的基本。不要让人浪费时间猜你想表达什么。

还有前面

>相同的文件用未汉化的tx2打开是正常的。

我完全不知道你在说什么。什么软件什么版本，什么平台，什么意思。

**Comment by shikelong** [comment]
![image](https://cloud.githubusercontent.com/assets/4499997/9022784/73b7a7d0-38b5-11e5-8f57-0378f40ef0b2.png)

重新装了一遍。 安装了packageController和你的插件。 打开中文文件还是有这个问题。 描述完毕。

**Comment by rexdf** [comment]
不装任何插件的情况下，是否是框框。如果是。我也没有办法。


不装任何插件的原版sublime text 3 win x64如果不是框框，那么我会关注。

**Comment by shikelong** [comment]
原版 sublime tx3. win.64 .只装了packageControl。       打开中文文件就是框框。 说的很明白了。

能否说明白你的本地化需要删除什么文件？   我把st3卸载了。把st3的package文件夹删除了。然后重新安装都还是那样。

**Comment by rexdf** [comment]
那么怎么个汉化不完全法？

**Comment by shikelong** [comment]
就是tab的汉字和sidebar的汉字有问题。你理解能力真捉急

**Comment by rexdf** [comment]
看看你自己什么素质

**Comment by rexdf** [comment]
我从来没见过说什么tx2是什么鬼东西，你看看你自己混乱的逻辑。

![a](https://cloud.githubusercontent.com/assets/4038241/9023085/997f49d2-38bf-11e5-930a-36a8b4d28e99.png)
