### ISSUE TITLE
Sublime 3083没有选择语言的选项，删除插件后，菜单栏依然是中文

### ISSUE THREAD

**Issue by Mark24Code** [rexdf/Chinese-Localization#6]

**Comment by rexdf** [comment]
什么系统？是通过package control安装的吗？ 关于善后问题确实没有做，一个折中做法是切换英文再在package control中卸载。印象中3083在早期测试过，没啥问题啊。确认你的Help下面没有？包括重启sublime.

**Comment by Mark24Code** [comment]
貌似是，没有切换到英文，直接卸载，会出现中英并存的状态，而且，再次重装的时候，帮助那边的切换语言的就没了。后来我是删掉了 sublime-menu文件，就变回全英文了。
之前没留意，帮助那边可以切换文字，以为装上了就切换不了了，所以急于卸载掉，就出现了上面的问题。现在又装了，在用了~~~
