### ISSUE TITLE
删除包之后，如何把菜单栏改回英文

### ISSUE THREAD

**Issue by Howld** [rexdf/Chinese-Localization#7]
我看了Main.sublime.menu，是这个文件被替换了吗？（debian8）

**Comment by rexdf** [comment]
看项目主页上的动态图片。Help/Lanuage选择英文就好。本来就是三语言切换的。

**Comment by Howld** [comment]
切换试过了，没反应，重新打开也一样

**Comment by rexdf** [comment]
是重新安装，换回英文再删除吗？中文状态删除包是换不回去的。

**Comment by Howld** [comment]
不是，我安装了，但是不能切换到英文，还是因为之前中文状态删除之后，现在重新安装，导致切换不了？

**Comment by rexdf** [comment]
你的情况有点奇怪。我等会弄个Debian看看。你是通过Package Control安装的吗？

如果要删除这个插件，最好是先用这个插件的菜单切换到英文再删除。也就是说这个插件自己能恢复英文状态。

那么繁体中文，日文能切换吗？只能简体中文状态了？

如果可以，<kbd>Ctrl</kbd>+<kbd>`</kbd>打开控制台，切换语言到英文，然后把控制台最后几行日志拷贝出来我看看。

**Comment by Howld** [comment]
是通过Package Control安装的，但没有日文切换选项（版本？），看日志是路径错了，应该怎么改？
Traceback (most recent call last):
  File "./sublime_plugin.py", line 320, in run_
  File "./Localization.py", line 97, in run
  File "./Localization.py", line 75, in set_language
IOError: [Errno 2] No such file or directory: '/home/dev/EN.zip'

**Comment by rexdf** [comment]
难道你是sublime text 2?

**Comment by Howld** [comment]
嗯

**Comment by rexdf** [comment]
好久没有维护sublime text2了…… 而且那个版本我只在windows做过测试。sbt3非常容易安装和那啥的。因为sbt2用的python2的一些不兼容性，最新的几个特性都没有对sbt2做兼容，原来日语也没写进去啊。貌似是相对目录的问题，我等会修正下。

**Comment by Howld** [comment]
嗯，辛苦了(^_^)∠※

**Comment by rexdf** [comment]
已更新 等Package Control更新 最长大约一小时左右
