### ISSUE TITLE
Can't switch Menu to English after remove the package

### ISSUE THREAD

**Issue by Hackice** [rexdf/Chinese-Localization#8]
and there is no "Language" option in the help menu.

<img width="376" alt="2016-05-24 2 58 31" src="https://cloud.githubusercontent.com/assets/12789614/15495073/794686b8-21c0-11e6-8297-38eb502fb474.png">

——Sublime Text Build 3114 with OS X 10.11.5

**Comment by rexdf** [comment]
You need to swith to English before uninstall this plugins. You can install it and uninstall it again.

In the future version, I will make it to swith automatically to English when uninstalling.
